# Generated by Django 6.0.1 on 2026-01-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_db', models.CharField(max_length=100)),
                ('email_db', models.EmailField(max_length=254, unique=True)),
                ('pass_db', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_csv_files/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('predictions', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='myapp.user_db')),
            ],
        ),
    ]
